GET {{baseUrl}}/common/tools/TEST-前女友/search
Accept: application/json

###

DELETE {{baseUrl}}/common/tools/categories?classKey=TEST-前女友
Content-Type: application/json
X-Token:{{X-Token}}

###

POST {{baseUrl}}/common/tools/categories
Content-Type: application/json
X-Token:{{X-Token}}

{
  "classKey":"TEST-前女友",
  "classNum": 1
}

###

PUT {{baseUrl}}/common/tools/categories
Content-Type: application/json
X-Token:{{X-Token}}

{
  "classKey":"TEST-前女友",
  "classNum": 2
}

###